### ISSUE TITLE
Zombie_Controller.js expects "Player" tag

### ISSUE THREAD

**Issue by n-krueger** [n-krueger/penguin-massacre#3]
The zombie script scans for GameObjects tagged with the "Player" tag. Currently, this tag does not exist.

**Comment by vincko** [comment]
Solving this by rewriting the Zombie_Controller.js Script into c#. I will also split it into multiple MonoBehaviours.

**Comment by vincko** [comment]
This should be resolved now. I added the "Player" tag to the player prefab. Please confirm @n-krueger

**Comment by n-krueger** [comment]
Yep, #4 closes this issue.
